#!/bin/bash

echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" > .env.local
echo "NEXT_PUBLIC_AUTHORIZATION_TOKEN=$NEXT_PUBLIC_AUTHORIZATION_TOKEN" >> .env.local
echo "NEXT_PUBLIC_THE_MOVIE_DB_IMAGE_BASE_URL=$NEXT_PUBLIC_THE_MOVIE_DB_IMAGE_BASE_URL" >> .env.local

npm run start
