version: '3'

services:
  front-end:
    build: '.'
    container_name: what-to-watch-tonight
    image: what-to-watch-tonight_frontend
    working_dir: /app
    env_file:
      - docker.env
    expose:
      - 3000
    ports:
      - 80:3000
    networks:
      - wtwt

networks:
  wtwt:
    name: wtwt
    driver: bridge
