import React from 'react';
import { render } from '@testing-library/react';
import '@testing-library/jest-dom';
import RootLayout from '../../app/layout';
import Home from '../../app/page';
import { metadata } from '../../app/layout';

describe('RootLayout', () => {
  it('Renderizando o layout raiz', () => {
    const { container } = render(
      <RootLayout>
        <Home />
      </RootLayout>,
    );
    expect(container).toBeTruthy();
    expect(container).toMatchSnapshot();
  });

  it('Verifica a estrutura HTML e a classe de fonte', () => {
    const { getByText, container } = render(
      <RootLayout>
        <div>Teste de Conteúdo</div>
      </RootLayout>,
    );
    const htmlElement = container.querySelector('html');
    expect(htmlElement).toBeInTheDocument();
    expect(htmlElement).toHaveAttribute('lang', 'en');

    const bodyElement = container.querySelector('body');
    expect(bodyElement).toBeInTheDocument();
    expect(bodyElement).toHaveClass('className');
    expect(bodyElement).toContainElement(getByText('Teste de Conteúdo'));
  });

  it('Verifica os metadados', () => {
    expect(metadata.title).toBe('Create Next App');
    expect(metadata.description).toBe('Generated by create next app');
  });
});
