#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run typecheck && \
npm run lint && \
npm run format && \
npm run test:unit || {
  echo "Erro: Verifique as cobertura ou se algum teste falhou."
  exit 1
}

exit 0
